[build]
builder = "nixpacks"

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18.x"
NIXPACKS_BUILD_CMD = "npm install -g pnpm && pnpm install && pnpm run build:production"
NIXPACKS_START_CMD = "pnpm start"
