[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install"]

[phases.build]
cmds = ["pnpm run build:production"]

[start]
cmd = "pnpm start"
