[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build:production"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
