[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node dist/server/node-build.mjs"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[domains]
main = "www.sentrysol.xyz"

[environment]
NODE_ENV = "production"
PORT = "3000"
