[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build:production"

[deploy]
startCommand = "node dist/server/node-build.mjs"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_NODE_VERSION = "18.x"
