[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install && pnpm run build:production"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
PORT = "3000"
